### ISSUE TITLE
Refiner/Infuser eat items if "not enough"

### ISSUE THREAD

**Issue by Soulrift** [jaredlll08/Fluxed-Crystals#26]
If an item requires 32 of a shard to craft, and you put 31 in, you'll end up losing all shards.  Machine needs to ping the config and not begin processing until enough items are there

**Comment by gh0st31337** [comment]
I can concur this issue, tried creating a reward bag seed using 1 or 2 bags at a time as I got them and it just ate them all.  It didn't actually work until I put 10 bags in at once.

**Comment by Soulrift** [comment]
The goal is to eventually have the refiner and infuser consume "stacks" of materials... ie... will wait til 16 shards are in the system, and pull all 16 at once.

**Comment by Eunomiac** [comment]
Just a request to raise the priority on this bug, because it's a bad one:  It kills automation, causes costly resource loss, and is not especially obvious to the player---in that items simply vanish out of the Refiner, giving the player no indication as to what happened.

Isn't the solution as simple as a conditional check before the Refiner starts to run, verifying the input stack size is equal to or greater than the quantity required?

**Comment by jaredlll08** [comment]
Sorry, I have been burn't out of Fluxed-Crystals, im hoping @Soulrift can get to this?

Also I am in the middle of rewriting modtweaker2 (which I haven't given enough of my time to lately)

**Comment by Eunomiac** [comment]
Aww, I'm sorry to hear that, I really enjoy Fluxed-Crystals!  Good on you for admitting the burnout---too many prefer to leave us hanging.

Apologies in advance for the unsolicited advice, but may I ask, when was the last time you just sat down and played some Minecraft for gits and shiddles?  (I've been working on a map for a long, long... _LONG long_ ... time, and burnt out completely for a while.  Then I picked up ME^4, and didn't even get halfway through it before I found myself excited to return to my own map.)  I'm sure it doesn't work like that for everyone, but I do know modding has this insidious way of eating away at your "playing for fun" time, until it's gone completely---and that's not a good thing, because it's the game, not the code, y'all fell in love with in the first place!

**Comment by jaredlll08** [comment]
Actually recently :) I've been playing jadedcat's Magical Farm 3, it is very well done, but hasnt made me want to go back to coding FC... but maybe ill do some tonight, because now im burn't out of MF3 and ModTweaker2 ;,,;

**Comment by Eunomiac** [comment]
Nah, don't force yourself to go back---that's just about the worst cure for burnout ever.  Keep playing Magical Farm 3 instead!  Just do what I do and have the "work stuff" open in the background in case the spark strikes just as you happen to minimize the game ;)
