### ISSUE TITLE
Machines aren't working.

### ISSUE THREAD

**Issue by Badcholo** [jaredlll08/Fluxed-Crystals#58]
The machines are not working properly.
Please make crafting recipes for processing. It currently doesn't work and the mod is useless. 
how do you power the machine blocks? do they use RF? This looks like a simple mod that has just been made way the freak too confusing. Please allow us to Pulverize the materials using Thermal expansion and then smelt the output. Give the machines special names like Chunk Processor or Chunk crusher so we know what to put where. how is it that the power soil uses power RF and the blocks don't? is it a bug? dang this mod is making me mad, it shouldn't be this complicated. i hate the processing animation by the way, it needs to be sync.
Crafting recipe for making the product smaller instead of the machine consuming 32 items at a time would be best. Crafting it down to 1 item to smelt of compact or crush would be best.

**Comment by jaredlll08** [comment]
Invalid issue.
My mod is called "Fluxed-Crystals"
Fluxed as in redstone flux as in RF.
And I am sorry that the mod makes you mad, but you will just have to deal with it.
in regards to the name change, this is complete bullshit, for the following reasons:
it is exactly the same as the current names, crusher = cutter, except it isn't fucking crushing, it is cutting,
Gem Refiner, Refine = process, for example, you would say "sugar was refined by boiling it in huge iron vats"
not
"sugar was processed by boiling it in huge iron vats".
Maybe a reason the machines don't work is because you aren't powering them.

Maybe next time do some research before you go shit talking a mod.

**Comment by Badcholo** [comment]
Crusher = Cutter, but what does it cut?
Gem Refiner = Process, but what does it process?
The machines were powered by RF. Sorry if i sounded rude, but i had a lot of trouble just getting this far. I have made a clip to show you that i can reproduce the issue. Please tell me what i am doing wrong. I still don't know what to do with the Rough Gold Chunks that i harvested from the plants.
Again, i'm sorry, I was going to make a Mod Showcase, because i really like this idea.
You should know, Time is valuable, I'm study up on the mods very well to find bugs or issues.
https://www.dropbox.com/s/e0gtg5eolx4bgqe/javaw%202015-04-24%2017-18-09-485.avi?dl=0

**Comment by jaredlll08** [comment]
ok so this is the process...
make a seed infuser, infuse universal seeds into seed of desired type
make powered soil
plant seeds onto powered soil
power the powered soil
wait for seeds to grow, harvest seeds (right click or just break)
place down the rough chunk onto the ground.
break the rough chunk with a crystal hammer
put the rough shards into a gem cutter.
put the smooth shards into a gem refiner
???
profit
